// Javascript con frases
var i = 0;
var arreglo = new Array();
arreglo[i] = "El que no está consigo mismo no está con nadie. Fernando González";
i = i + 1;
arreglo[i] = "Tranquilo Pedro, hablemos bajo, acuérdate que ellos tienen revolver y nosotros no. Enrique Buenaventura";
i = i + 1;
arreglo[i] = "Quien tiene las flores no necesita a Dios. Alberto Caeiro";
i = i + 1;
arreglo[i] = "Encuéntrame allí donde todo es gris y no se sufre. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Nunca te vuelvas una persona seria. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Adelántate a la muerte, precísale una cita. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Para la timidez la autodestrucción. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Jamás ahorres. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Nunca dejes de ser niño, aunque tengas los ojos en la nuca. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Si dejas obra muere tranquilo. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Que nadie sepa tu nombre y que nadie amparo te dé. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Todo es fantasía menos la muerte. Ramón Gómez de la Serna";
i = i + 1;
arreglo[i] = "¡Cómo cae la luna sobre los cementerios! ¡Cae de lleno! Ramón Gómez de la Serna";
i = i + 1;
arreglo[i] = "En el desierto está dios sin los hombres. Balzac";
i = i + 1;
arreglo[i] = "Sólo donde hay tumbas hay resurrecciones. Nietzsche";
i = i + 1;
arreglo[i] = "Estamos hechos de la misma sustancia de los sueños y a nuestra breve vida la circunda el sueño. Shakespeare";
i = i + 1;
arreglo[i] = "Todo lo sólido se desvanece en el aire";
i = i + 1;
arreglo[i] = "Un árbol, un camino. Beckett";
i = i + 1;
arreglo[i] = "No busques ni creas todo está oculto. F. Pessoa";
i = i + 1;
arreglo[i] = "Cada gesto interrumpe un sueño. F. Pessoa";
i = i + 1;
arreglo[i] = "¡El mundo entero no existe para mí! F. Pessoa";
i = i + 1;
arreglo[i] = "No tengo ambiciones ni deseos, ser poeta no es una ambición mía, es mi manera de estar solo. F. Pessoa";
i = i + 1;
arreglo[i] = "Las manos no son verdaderas ni reales, son misterios que habitan nuestra vida. F. Pessoa";
i = i + 1;
arreglo[i] = "¿No valdría la pena encerrarnos en el sueño, y olvidar la vida para que la muerte nos olvidase? F. Pessoa";
i = i + 1;
arreglo[i] = "¿Y si nada existiese? ¿Y si todo fuese, de algún modo, absolutamente cosa ninguna? F. Pessoa";
i = i + 1;
arreglo[i] = "¿Por qué se muere? Tal vez porque no se sueña bastante. F. Pessoa";
i = i + 1;
arreglo[i] = "Quiero ganarme con mi escritura el pan y la sal. Sylvia Plath";
i = i + 1;
arreglo[i] = "El amor es un artificio desesperado para ocupar el lugar del padre y de la madre. Sylvia Plath";
i = i + 1;
arreglo[i] = "No ser perfecta duele. Sylvia Plath";
i = i + 1;
arreglo[i] = "Doy al mundo mi intensidad y mi pasión en diminutas cucharadas homeopáticas. Sylvia Plath";
i = i + 1;
arreglo[i] = "Necesito una vocación y sentirme productiva, pero lo que de verdad me siento es inútil. Ignorante. Sylvia Plath";
i = i + 1;
arreglo[i] = "Un pánico absoluto y destructor: aquí terminan todos los diarios. Sylvia Plath";
i = i + 1;
arreglo[i] = "A la mujer del metro le dije: Mira, soy humana; me miró a los ojos y me creyó. Sylvia Plath";
i = i + 1;
arreglo[i] = "Yo todavía estoy cruda. Sylvia Plath";
i = i + 1;
arreglo[i] = "Siempre es peor al día siguiente. Séneca";
i = i + 1;
arreglo[i] = "Languidece la virtud sin adversarios. Séneca";
i = i + 1;
arreglo[i] = "Cuando recuerdo lo que dije, tengo envidia de los mudos. Séneca";
i = i + 1;
arreglo[i] = "Ya es una buena cosa, en las mujeres malas, que sean abiertamente malas. Séneca";
i = i + 1;
arreglo[i] = "Emprende, alma mía, la gesta prolijamente meditada; arráncate de las miserias de la humanidad. Séneca";
i = i + 1;
arreglo[i] = "No nací en un rincón remoto, mi patria es el mundo entero. Séneca";
i = i + 1;
arreglo[i] = "La naturaleza no nos otorga la virtud, ser bueno es un arte. Séneca";
i = i + 1;
arreglo[i] = "Los verdaderos bienes, sólidos y eternos, son los de la razón. Séneca";
i = i + 1;
arreglo[i] = "La vida es como una leyenda: no importa que sea larga, si no que esté bien narrada. Séneca";
i = i + 1;
arreglo[i] = "Lo que las leyes no prohíben, puede prohibirlo la honestidad. Séneca";
i = i + 1;
arreglo[i] = "La vida es un asunto de guerra. Séneca";
i = i + 1;
arreglo[i] = "Los pequeños dolores son locuaces, los grandes callan estupefactos. Séneca";
i = i + 1;
arreglo[i] = "La vida es como una escuela de gladiadores: convivir y pelear. Séneca";
i = i + 1;
arreglo[i] = "Nadie tiene la muerte en perspectiva. Séneca";
i = i + 1;
arreglo[i] = "La mayor rémora de la vida es la espera del mañana y la pérdida del día de hoy. Séneca";
i = i + 1;
arreglo[i] = "Sé esclavo del saber, si quieres ser verdaderamente libre. Séneca";
i = i + 1;
arreglo[i] = "El desgraciado es cosa sagrada. Séneca";
i = i + 1;
arreglo[i] = "Incierto es el lugar donde la muerte espera; espérala, pues, en todo lugar. Séneca";
i = i + 1;
arreglo[i] = "No hay mayor causa de llanto que no poder llorar. Séneca";
i = i + 1;
arreglo[i] = "El pobre no es el que tiene poco si no el que desea más. Séneca";
i = i + 1;
arreglo[i] = "Absoluta rebelión contra la totalidad de la simpleza. A. Jarry";
i = i + 1;
arreglo[i] = "No habremos demolido todo hasta que no hayamos demolido incluso los escombros. A. Jarry";
i = i + 1;
arreglo[i] = "No creemos en más aplauso que el del silencio. A. Jarry";
i = i + 1;
arreglo[i] = "Odio a mis maestros y sus intachables hipocresías. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Odio mi cuerpo y mi alma. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Odio a Cali, una ciudad con unos habitantes que caminan y caminan. Andrés Caicedo";
i = i + 1;
arreglo[i] = "Odio todo lo que tengo de cielo para mirar, porque nunca he podido encontrar en él la parte exacta donde habita Dios. Andrés Caicedo";
i = i + 1;
arreglo[i] = "¿Jamás notaste cómo las pupilas se le iban dilatando, dilatando, hasta ponerse delgadas y largas? Andrés Caicedo";
i = i + 1;
arreglo[i] = "Odio las malditas horas de estudios por conseguir una buena nota. Andrés Caicedo";
i = i + 1;
arreglo[i] = "¿Cómo será la sangre que le sale, caliente o fría? Andrés Caicedo";
i = i + 1;
arreglo[i] = "¿No florece nuestra alma sino en el fondo de las noches de tormenta? Maeterlinck";
i = i + 1;
arreglo[i] = "Todo hombre es un Shakespeare en sus sueños. Se ha dicho. Maeterlinck";
i = i + 1;
arreglo[i] = "El teatro hoy, no se detiene ya en los efectos de la desgracia, sino en la desgracia misma. Maeterlinck";
i = i + 1;
arreglo[i] = "Esperemos en silencio; tal vez oigamos dentro de poco el murmullo de los dioses. Maeterlinck";
i = i + 1;
arreglo[i] = "¿Es que la belleza necesita ser comprendida para existir? Maeterlinck";
i = i + 1;
arreglo[i] = "En la desgracia es principalmente cuando el silencio nos rodea. Maeterlinck";
i = i + 1;
arreglo[i] = "El silencio es el elemento en que se forman las cosas grandes. Maeterlinck";
i = i + 1;
arreglo[i] = "¿En el fondo de qué mar de misterios vivimos? Maeterlinck";
i = i + 1;
arreglo[i] = "Un poeta trágico ha recorrido, con la antorcha de la poesía en la mano, los laberintos del destino. Maeterlinck";
i = i + 1;
arreglo[i] = "Todo lo que puede aprenderse sin angustia nos empequeñece. Maeterlinck";
i = i + 1;
var ranNum = Math.round(Math.random() * ((arreglo.length) - 1));
var frase = arreglo[ranNum];
mensajes = "";


var i = 0;
var arreglo = new Array();

arreglo[i] = "<img src='img/titere1.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere2.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere3.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere4.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere5.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere6.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere7.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere8.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere9.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere10.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere11.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere12.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere13.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere14.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere15.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/titere16.png' alt='titere' />";
i = i + 1;
arreglo[i] = "<img src='img/Titere.png' alt='titere' />";
i = i + 1;

var ranNum = Math.round(Math.random() * ((arreglo.length) - 1));
var titeres = arreglo[ranNum];
mensajes = "";


// Javascript cambiar elementos de block a none y de none a block
function cambiar(esto) {
    vista = document.getElementById(esto).style.display;
    if (vista == 'none')
        vista = 'block';
    else
        vista = 'none';

    document.getElementById(esto).style.display = vista;
}

